
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.RadioButton rbtVectorial;
	private global::Gtk.RadioButton rbtRasterized;
	private global::Gtk.DrawingArea canvas;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button btnDrawLines;
	private global::Gtk.Button btnReset;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.rbtVectorial = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Vectorial"));
		this.rbtVectorial.CanFocus = true;
		this.rbtVectorial.Name = "rbtVectorial";
		this.rbtVectorial.DrawIndicator = true;
		this.rbtVectorial.UseUnderline = true;
		this.rbtVectorial.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox1.Add (this.rbtVectorial);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rbtVectorial]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.rbtRasterized = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Rasterized"));
		this.rbtRasterized.CanFocus = true;
		this.rbtRasterized.Name = "rbtRasterized";
		this.rbtRasterized.DrawIndicator = true;
		this.rbtRasterized.UseUnderline = true;
		this.rbtRasterized.Group = this.rbtVectorial.Group;
		this.hbox1.Add (this.rbtRasterized);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rbtRasterized]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.canvas = new global::Gtk.DrawingArea ();
		this.canvas.Name = "canvas";
		this.vbox1.Add (this.canvas);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.canvas]));
		w4.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnDrawLines = new global::Gtk.Button ();
		this.btnDrawLines.CanFocus = true;
		this.btnDrawLines.Name = "btnDrawLines";
		this.btnDrawLines.UseUnderline = true;
		this.btnDrawLines.Label = global::Mono.Unix.Catalog.GetString ("Draw lines");
		this.hbox2.Add (this.btnDrawLines);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnDrawLines]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnReset = new global::Gtk.Button ();
		this.btnReset.CanFocus = true;
		this.btnReset.Name = "btnReset";
		this.btnReset.UseUnderline = true;
		this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.hbox2.Add (this.btnReset);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnReset]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
